--- 
apiVersion: v1
kind: Service
metadata:
  name: ms-lb-service
  labels:
    app: ms-lb-service
spec:
  ports:
  - port: 8080
    name: ms-api
  - port: 9000
    name: edge-ui
  type: LoadBalancer
  selector:
    app: ms