--- 
apiVersion: v1
kind: Service
metadata:
  name: ms
  labels:
    app: ms
spec:
  ports:
  - port: 10389
    name: openldap
  - port: 8080
    name: ms-api
  - port: 9000
    name: edge-ui
  clusterIP: None
  selector:
    app: ms
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ms-pdb
spec:
  selector:
    matchLabels:
      app: ms
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ms
spec:
  selector:
    matchLabels:
      app: ms
  serviceName: ms
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: ms
    spec:
      securityContext:
        runAsUser: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - ms
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: apigee-ms
        imagePullPolicy: Always
        image: "eu.gcr.io/gsj-k8s-training/apigee-opdk:8"
        resources:
          requests:
            memory: ".25Gi"
            cpu: ".25"
        ports:
        - containerPort: 10389
          name: openldap
        - containerPort: 8080
          name: ms-api
        - containerPort: 9000
          name: edge-ui
        command:
        - sh
        - -c
        - "cp /hwreqs/hardware_requirements.properties /opt/apigee/apigee-setup/conf/hardware_requirements.properties && sudo HOSTIP=\"$(hostname).ms.default.svc.cluster.local\" /opt/apigee/apigee-setup/bin/setup.sh -p ms -f /config/5-node.config && while true ; do sleep 1 ; done" 
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep 2181 | fgrep LISTEN"
          initialDelaySeconds: 30
          timeoutSeconds: 15
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep 2181 | fgrep LISTEN"
          initialDelaySeconds: 30
          timeoutSeconds: 15
        volumeMounts:
        - name: datadir
          mountPath: /opt/apigee/data
        - name: vardir
          mountPath: /opt/apigee/var
        - name: configmap-volume
          mountPath: /config/5-node.config
          readOnly: true
          subPath: 5-node.config
        - name: hwreqs-volume
          mountPath: /hwreqs/hardware_requirements.properties
          readOnly: true
          subPath: hardware_requirements.properties
      volumes:
      - name: configmap-volume
        configMap:
          defaultMode: 0755
          name: node.config
      - name: hwreqs-volume
        configMap:
          defaultMode: 0755
          name: hwreqs.config
      securityContext:
        runAsUser: 999
        fsGroup: 998
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: vardir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
