--- 
apiVersion: v1
kind: Service
metadata:
  name: mshs
  labels:
    app: mshs
spec:
  ports:
  - port: 10389
    name: openldap
  - port: 8080
    name: ms-api
  - port: 9000
    name: edge-ui
  clusterIP: None
  selector:
    app: ms
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ms-pdb
spec:
  selector:
    matchLabels:
      app: ms
  maxUnavailable: 0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ms
spec:
  selector:
    matchLabels:
      app: ms
  serviceName: mshs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: ms
    spec:
      securityContext:
        runAsUser: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - ms
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: apigee-ms
        imagePullPolicy: Always
        image: "eu.gcr.io/gsj-k8s-training/apigee-opdk:16"
        resources:
          requests:
            memory: ".5Gi"
            cpu: ".25"
        ports:
        - containerPort: 10389
          name: openldap
        - containerPort: 8080
          name: ms-api
        - containerPort: 9000
          name: edge-ui
        command:
        - sh
        - -c
        - "sudo chown apigee:apigee /opt/apigee && sudo chmod -R 775 /opt/apigee/data /opt/apigee/var && sudo HOSTIP=\"$(hostname).mshs.default.svc.cluster.local\" /opt/apigee/apigee-setup/bin/setup.sh -p ms -f /config/opdk-ds-cluster.config && while true ; do sleep 1 ; done" 
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep LISTEN"
          initialDelaySeconds: 300
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep LISTEN"
          initialDelaySeconds: 300
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /opt/apigee/data
        - name: vardir
          mountPath: /opt/apigee/var
        - name: configmap-volume
          mountPath: /config/opdk-ds-cluster.config
          readOnly: true
          subPath: opdk-ds-cluster.config
        - name: license-volume
          mountPath: /license/license.txt
          readOnly: true
          subPath: license.txt
        - name: org-config-volume
          mountPath: /org/org.config
          readOnly: true
          subPath: org.config
      volumes:
      - name: configmap-volume
        configMap:
          defaultMode: 0755
          name: opdk-ds-cluster.config
      - name: license-volume
        configMap:
          defaultMode: 0755
          name: license.config
      - name: org-config-volume
        configMap:
          defaultMode: 0755
          name: org.config
      securityContext:
        runAsUser: 999
        fsGroup: 998
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: vardir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
