--- 
apiVersion: v1
kind: Service
metadata:
  name: psmasterhs
  labels:
    app: psmasterhs
spec:
  ports:
  - port: 22
    name: ssh
  - port: 1103
    name: jmx
  - port: 4530
    name: cache
  - port: 5432
    name: qpid-ps-comms
  - port: 8084
    name: mgmt-port
  clusterIP: None
  selector:
    app: ps-master
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ps-master-pdb
spec:
  selector:
    matchLabels:
      app: ps-master
  maxUnavailable: 0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ps-master
spec:
  selector:
    matchLabels:
      app: ps-master
  serviceName: psmasterhs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: ps-master
    spec:
      securityContext:
        runAsUser: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - ps-master
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: apigee-ps-master
        imagePullPolicy: Always
        image: "eu.gcr.io/gsj-k8s-training/apigee-opdk:16"
        resources:
          requests:
            memory: ".3Gi"
            cpu: ".3"
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 1103
          name: jmx
        - containerPort: 4530
          name: cache
        - containerPort: 5432
          name: qpid-ps-comms
        - containerPort: 8084
          name: mgmt-port
        command:
        - sh
        - -c
        - "sudo mkdir -p /opt/apigee/var/log && sudo chown apigee:apigee /opt/apigee && sudo chown -R apigee:apigee /opt/apigee/var && sudo chmod -R 775 /opt/apigee/var && sudo chown -R apigee:apigee /opt/apigee/data && sudo chmod -R 700 /opt/apigee/data && sudo HOSTIP=\"$(hostname).psmasterhs.default.svc.cluster.local\" /opt/apigee/apigee-setup/bin/setup.sh -p ps -f /config/opdk-ds-cluster.config && while true ; do sleep 1 ; done" 
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep LISTEN"
          initialDelaySeconds: 300
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep LISTEN"
          initialDelaySeconds: 300
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /opt/apigee/data
        - name: vardir
          mountPath: /opt/apigee/var
        - name: configmap-volume
          mountPath: /config/opdk-ds-cluster.config
          readOnly: true
          subPath: opdk-ds-cluster.config
        - name: license-volume
          mountPath: /license/license.txt
          readOnly: true
          subPath: license.txt
      volumes:
      - name: configmap-volume
        configMap:
          defaultMode: 0755
          name: opdk-ds-cluster.config
      - name: license-volume
        configMap:
          defaultMode: 0755
          name: license.config
      securityContext:
        runAsUser: 999
        fsGroup: 998
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: vardir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
