--- 
apiVersion: v1
kind: Service
metadata:
  name: qshs
  labels:
    app: qshs
spec:
  ports:
  - port: 1102
    name: jmx
  - port: 4529
    name: cache
  - port: 5672
    name: qpid-comms
  - port: 8083
    name: qpid-mgmt-port
  clusterIP: None
  selector:
    app: qs
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: qs-pdb
spec:
  selector:
    matchLabels:
      app: qs
  maxUnavailable: 0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qs
spec:
  selector:
    matchLabels:
      app: qs
  serviceName: qshs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: qs
    spec:
      securityContext:
        runAsUser: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - qs
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: apigee-qs
        imagePullPolicy: Always
        image: "eu.gcr.io/gsj-k8s-training/apigee-opdk:16"
        resources:
          requests:
            memory: ".5Gi"
            cpu: ".25"
        ports:
        - containerPort: 1102
          name: jmx
        - containerPort: 4529
          name: cache
        - containerPort: 5672
          name: qpid-comms
        - containerPort: 8083
          name: qpid-mgmt-port
        command:
        - sh
        - -c
        - "sudo chown apigee:apigee /opt/apigee && sudo HOSTIP=\"$(hostname).qshs.default.svc.cluster.local\" /opt/apigee/apigee-setup/bin/setup.sh -p qs -f /config/opdk-ds-cluster.config && while true ; do sleep 1 ; done" 
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep LISTEN"
          initialDelaySeconds: 300
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep LISTEN"
          initialDelaySeconds: 300
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /opt/apigee/data
        - name: vardir
          mountPath: /opt/apigee/var
        - name: configmap-volume
          mountPath: /config/opdk-ds-cluster.config
          readOnly: true
          subPath: opdk-ds-cluster.config
        - name: license-volume
          mountPath: /license/license.txt
          readOnly: true
          subPath: license.txt
        - name: org-config-volume
          mountPath: /org/org.config
          readOnly: true
          subPath: org.config
      volumes:
      - name: configmap-volume
        configMap:
          defaultMode: 0755
          name: opdk-ds-cluster.config
      - name: license-volume
        configMap:
          defaultMode: 0755
          name: license.config
      - name: org-config-volume
        configMap:
          defaultMode: 0755
          name: org.config
      securityContext:
        runAsUser: 999
        fsGroup: 998
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: vardir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
