apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: datastore-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: apigee.google.com/v1
    resource: datastores
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://datastore-controller.metacontroller/datastore-sync
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datastore-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastore-controller
  template:
    metadata:
      labels:
        app: datastore-controller
    spec:
      containers:
      - name: controller
        image: metacontroller/nodejs-server:0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: hooks
          mountPath: /node/hooks
      volumes:
      - name: hooks
        configMap:
          name: datastore-controller
---
apiVersion: v1
kind: Service
metadata:
  name: datastore-controller
  namespace: metacontroller
spec:
  selector:
    app: datastore-controller
  ports:
  - port: 80
