apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: orgs.apigee.google.com
spec:
  group: apigee.google.com
  version: v1
  scope: Namespaced
  names:
    plural: orgs
    singular: org
    kind: org
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["org_name","org_admin"]
          properties:
            org_name:
              type: "string"
              minimum: 1
            org_admin:
              type: "string"
              minimum: 1
            new_user:
              type: boolean
            user_name:
              type: "string"
              minimum: 1
            first_name:
              type: "string"
              minimum: 1
            last_name:
              type: "string"
              minimum: 1
            user_pwd:
              type: "string"
              minimum: 1
            router-replicas:
              type: "integer"
              minimum: 2
