apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: psslaves.apigee.google.com
spec:
  group: apigee.google.com
  version: v1
  scope: Namespaced
  names:
    plural: psslaves
    singular: psslave
    kind: psslave
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["replicants"]
          properties:
            replicants:
              type: "integer"
              minimum: 1
