apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routers.apigee.google.com
spec:
  group: apigee.google.com
  version: v1
  scope: Namespaced
  names:
    plural: routers
    singular: router
    kind: router
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["replicants","org"]
          properties:
            replicants:
              type: "integer"
              minimum: 2
