apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vhost.apigee.google.com
spec:
  group: google.apigee.com
  version: v1
  scope: Namespaced
  names:
    plural: vhosts
    singular: vhost
    kind: vhost
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["VHOST_NAME","VHOST_ALIAS"]
          properties:
            VHOST_NAME:
              type: "string"
              minimum: 1
            VHOST_ALIAS:
              type: "string"
              minimum: 1
